version: '3.8'
services:
  appdaf:
    build: .
    container_name: appdaf
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - appnet
  db:
    image: postgres:15
    container_name: appdaf_db
    restart: always
    environment:
      POSTGRES_DB: appdaf
      POSTGRES_USER: appdafuser
      POSTGRES_PASSWORD: appdafpass
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet
  nginx:
    image: nginx:latest
    container_name: appdaf_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html/public
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - appdaf
    networks:
      - appnet
volumes:
  db_data:
networks:
  appnet:
    driver: bridge
